name: md update
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0/5 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CSV_KEY: ${{ secrets.CSV_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - name: setup
        run: pip install -r requirements.txt

      - name: data decrypt
        run: python encode_decode.py
        env:
          ENC_DEC: 'DEC'

      - name: main
        run: python make_index_md_3.py

      - name: commit md
        run: |          
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ secrets.MY_EMAIL }}
          git add ./docs/index.md -A \
          && git diff --cached --exit-code \
          || (git add -A ./docs/index.md \
          && git commit -m "auto commit docs folder" \
          && git push)