on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.CSV_KEY }} > ./out.txt
      - uses: actions/upload-artifact@v4
        with:
          path: ./out.txt